### ISSUE TITLE
Проблема с подключением Pod-а.

### ISSUE THREAD

**Issue by AlexanderEBaranov** [SpectralDragon/LiteRoute#38]
Привет.
Почему-то при вот таком подключении pod "LightRoute" качается 2.1.19, при таком pod 'LightRoute', :git => 'https://github.com/SpectralDragon/LightRoute.git' качается  2.1.21 (то что надо). Есть очень большая необходимость в таком подключении pod 'LightRoute', чтоб выкачивалась  версия 2.1.21   - без указания адреса репозитория. Можешь поправить ?

**Comment by SpectralDragon** [comment]
Так как у меня нет доступа, то пожалуй я переименую репу и залью уже норм версию.

**Comment by AlexanderEBaranov** [comment]
дай знать откуда брать новую версию

**Comment by SpectralDragon** [comment]
Опубликовал с новым именем [LiteRoute](https://cocoapods.org/pods/LiteRoute).

Доступ от этого аккаунта у меня точно не пропадет)

**Comment by AlexanderEBaranov** [comment]
Большое спасибо)
